modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL="https://github.com/nitu2003/issues"
[[mods]]
modId="cfh"
version="${file.jarVersion}"
displayName="ColorfulHeads"
updateJSONURL="https://cfh.glycol.cn/update.json"
displayURL="https://cfh.glycol.cn"
logoFile="logo.png"
credits="Yeah, heads."
authors="Taskeren"
description='''
Hey! Look at these beautiful heads!
'''
